# fly.toml file generated for mtl15m on 2023-04-26T00:16:27Z

app = "mtl15m"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "yyz"
processes = []

[[services]]
  internal_port = 8043
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443