name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Use Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: fr_CA.UTF-8
        run: |
            sudo locale-gen fr_CA.UTF-8
            sudo update-locale LANG=fr_CA.UTF-8
      - name: Generate data
        run: tools/run_all.sh
      - name: npm install, build, and test
        uses: actions/setup-node@v3
        run: |
          npm ci
          npm run build --if-present
          npm run coverage
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage